name: automobile-service-backend
region: nyc

services:
  - name: backend
    dockerfile_path: backend/Dockerfile
    source_dir: backend
    github:
      repo: team-tensors/EAD-Automobile-Service-Management-System
      branch: main
      deploy_on_push: true
    
    # Environment variables
    envs:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: "8080"
    
    # Resource configuration
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month
    
    # Health check
    health_check:
      http_path: /actuator/health
      port: 8080
    
    # HTTP port
    http_port: 8080
    
    routes:
      - path: /
