name: automobile-service-backend
region: sgp1

services:
  - name: backend
    dockerfile_path: backend/Dockerfile
    source_dir: backend
    github:
      repo: team-tensors/EAD-Automobile-Service-Management-System
      branch: main
      deploy_on_push: true
    
    # Environment variables
    envs:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: "8080"
      - key: DB_URL
        value: jdbc:postgresql://db-postgresql-sgp1-83058-do-user-17134874-0.i.db.ondigitalocean.com:25060/defaultdb?sslmode=require
      - key: DB_USERNAME
        value: doadmin
      - key: DB_PASSWORD
        value: AVNS_QJ1Q82OmTgud72e4tib
        type: SECRET
      - key: JWT_SECRET
        value: your-jwt-secret-change-this-in-production
        type: SECRET
      - key: GOOGLE_CLIENT_ID
        value: your-google-client-id
      - key: GOOGLE_CLIENT_SECRET
        value: your-google-client-secret
        type: SECRET
      - key: FRONTEND_URL
        value: https://team-tensors.github.io/EAD-Automobile-Service-Management-System
    
    # Resource configuration
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # Health check
    health_check:
      http_path: /api/actuator/health
      port: 8080
    
    # HTTP port
    http_port: 8080
    
    routes:
      - path: /
